---
# file: roles/galera/tasks/main.yml
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - galera
    - galera-bootstrap
    - galera-config 
    - galera-firewall
    - galera-repo
    - galera-reset
    - galera-secure
    - galera-selinux
    - galera-users
    - galera-install
    - galera-pacemaker

- include_vars: "{{ ansible_os_family }}_packages.yml"
  tags:
    - galera
    - galera-bootstrap
    - galera-config 
    - galera-firewall
    - galera-repo
    - galera-reset
    - galera-secure
    - galera-selinux
    - galera-users
    - galera-install
    - galera-pacemaker
  when: galera_packages | length == 0

- include: reset.yml
  when: galera_reset_cluster is defined and
        galera_reset_cluster == true
  tags: [ galera, galera-reset ]

- include: repos.yml
  tags: [ galera, galera-repo ]

- include: install.yml
  tags: [ galera, galera-install ]

- include: firewall.yml
  when: galera_firewalld is defined and
        galera_firewalld == true
  tags: [ galera, galera-firewall ]

- include: config.yml
  tags: [ galera, galera-config ]

- include: secure.yml
  tags: [ galera, galera-secure ]

- include: user.yml
  tags: [ galera, galera-users ]

- include: bootstrap.yml
  tags: [ galera, galera-bootstrap ]

- include: pacemaker.yml
  when: galera_pacemaker_support is defined and
        galera_pacemaker_support == true
  tags: [ galera, galera-pacemaker ]
