---
# file: roles/galera/tasks/users.yml
- name: Creating the SST replication user
  mysql_user:
    name={{ galera_sst_user }}
    password={{ galera_sst_password }}
    priv=*.*:ALL,GRANT
    state=present
  when: inventory_hostname == galera_master
